### ISSUE TITLE
Green dye recipe

### ISSUE THREAD

**Issue by XtraDavido** [bodebojo/Crafted-Tweaks#3]
**Is your feature request related to a problem? Please describe.**
I cant mix yellow and blue dye to create green

**Describe the solution you'd like**
1 yellow dye + 1 blue dye = 2 green dye, 1 yellow dye + 1 light blue dye = 2 lime dye.

**Describe alternatives you've considered**
not yet

**Additional context**
not needed

**Comment by bodebojo** [comment]
Still need to do the lime recipe (My bad)

**Comment by bodebojo** [comment]
Will be added next update
