### ISSUE TITLE
Dye recipe changes

### ISSUE THREAD

**Issue by XtraDavido** [bodebojo/Crafted-Tweaks#4]
**Is your feature request related to a problem? Please describe.**
I don't like the dye conversion of gunpowder and glow ink

**Describe the solution you'd like**
Gunpowder should turn into gray dye, glow ink shouldn't turn into dye at all, since it's a dye by itself (used on signs)

**Comment by bodebojo** [comment]
Glow ink will remain a dye.
Will close this issue now.
